#!/bin/sh

set -e

# Script to do unpack of rootfs, ensures proper tear down
# of existing environment. Expects debian rootfs in
# /data/local/tmp/deb.tar.gz which it will delete after successful
# unpack of rootfs.

spath=$( cd "$(dirname "$0")" ; pwd -P )

if [ ! -f /data/local/tmp/androdeb/deb.tar.gz ]; then
	echo "Debian rootfs tar doesn't existing at /data/local/tmp/androdeb/deb.tar.gz"
	echo "Run androdeb with device connected first"
	exit 1
fi

if [ -d /data/local/tmp/androdeb/debian ]; then
	echo "androdeb environment already exists, doing a tear down"
	/data/local/tmp/androdeb/device-umount-all
	rm -rf /data/local/tmp/androdeb/debian
fi


gunzip /data/local/tmp/androdeb/deb.tar.gz
tar -xf /data/local/tmp/androdeb/deb.tar -C /data/local/tmp/androdeb/
rm /data/local/tmp/androdeb/deb.tar

echo "Unpack of rootfs successful!"
